#!/bin/bash
# Prevent QT from scaling the window to big.
export QT_AUTO_SCREEN_SCALE_FACTOR=0

# Basic start script for running MultiMC with the libs packaged with it.

function printerror {
    printf "$1"
    if which zenity >/dev/null; then zenity --error --text="$1" &>/dev/null;
    elif which kdialog >/dev/null; then kdialog --error "$1" &>/dev/null;
    fi
}

if [[ $EUID -eq 0 ]]; then
    printerror "This program should not be run using sudo or as the root user!\n"
    exit 1
fi


MMC_DIR="$(dirname "$(readlink -f "$0")")"
echo "MultiMC Dir: ${MMC_DIR}"

# Set up env - filter out input LD_ variables but pass them in under different names
export GAME_LIBRARY_PATH=${GAME_LIBRARY_PATH-${LD_LIBRARY_PATH}}
export GAME_PRELOAD=${GAME_PRELOAD-${LD_PRELOAD}}
export LD_LIBRARY_PATH="${MMC_DIR}/bin":$MMC_LIBRARY_PATH
export LD_PRELOAD=$MMC_PRELOAD
export QT_PLUGIN_PATH="${MMC_DIR}/plugins"
export QT_FONTPATH="${MMC_DIR}/fonts"

# Detect missing dependencies...
DEPS_LIST=""
for dep in 'osspd' 'libopenal-dev'; do
if ! dpkg -s $dep &>/dev/null; then
#echo "$dep is missing!"
DEPS_LIST+=$dep
fi
done
if [ "x$DEPS_LIST" = "x" ]; then
    # We have all our dependencies. Run MultiMC.
    echo "No missing dependencies found."

    # Just to be sure...
    chmod +x "${MMC_DIR}/bin/MultiMC"

    # Run MultiMC
    "${MMC_DIR}/bin/MultiMC" -d "${MMC_DIR}" "$@"

    # Exit with MultiMC's exit code.
    exit $?
else

    MESSAGE="Error: MultiMC/Minecraft is missing the following libraries that it needs to work correctly:\n\t${DEPS_LIST}\nPlease install them from your distribution's package manager."

    printerror "$MESSAGE"
    exit 1
fi
